image: gradle:8.1.1-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  tags:
    - pages-share
  script: "gradle sonarqube \
            -Dsonar.projectKey=ssc_tools_idea-plugins_tsie-code-generator_AYhNGgWHhizaQ_UPRZGA \
            -Dsonar.host.url=http://9000.grd2bd63.01pxwbcl.57488d.grapps.cn \
            -Dsonar.login=d939c9ea4d493f5faaadb3f76b58fe1f641448b4"
  cache:
    key: "gradle_cache"
    paths:
      - build
      - .gradle
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  allow_failure: true

