# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generator Plugin Doc Markdown Text
      env: # Or as an environment variable
        intellijPublishToken: ${{ secrets.INTELLIJPUBLISHTOKEN }}
      # 不打包 Kotlin 标准依赖：https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library
      run: ./gradlew markdownToHtml
    - name: Build with Gradle
      env: # Or as an environment variable
        intellijPublishToken: ${{ secrets.INTELLIJPUBLISHTOKEN }}
      # 不打包 Kotlin 标准依赖：https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library
      run: ./gradlew buildPlugin -Pkotlin.stdlib.default.dependency=false
    - name: Rename
      run: mv build/distributions/*.zip build/distributions/plugin.zip
    - name: Unpack Plugin Zip
      run: unzip -d tmp/ build/distributions/plugin.zip
    - uses: actions/upload-artifact@v2
      with:
        name: Database Generator
        path: tmp/**/*
